export const TOGGLE_WISHLIST = 'TOGGLE_WISHLIST';
export const GET_MOVIELIST = 'GET_MOVIELIST';
export const GET_MOVIE_DETAILS_PENDING = 'GET_MOVIE_DETAILS_PENDING';
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAILURE = 'GET_MOVIE_DETAILS_FAILURE';
export const GET_MOVIE_ID = 'GET_MOVIE_ID';